// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class User_Add_Index_Name : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_Add_Index_Name));
        
        string IMigrationMetadata.Id
        {
            get { return "201708140526236_User_Add_Index_Name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
