// <auto-generated />
namespace Project.Framework.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddTable_temp_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTable_temp_table));
        
        string IMigrationMetadata.Id
        {
            get { return "201803061323315_AddTable_temp_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
